#zmiany w CMakeCache:
#24c24
#< BUILD_EXAMPLES:BOOL=OFF
#---
#> BUILD_EXAMPLES:BOOL=ON
#30c30
#< BUILD_TESTING:BOOL=OFF
#---
#> BUILD_TESTING:BOOL=ON
#512c512
#< ITK_USE_PATENTED:BOOL=ON
#---
#> ITK_USE_PATENTED:BOOL=OFF


CMAKE="/Applications/CMake 2.8-6.app/Contents/bin/cmake"
"$CMAKE" -G Xcode \
-DBUILD_EXAMPLES:BOOL=OFF \
-DBUILD_TESTING:BOOL=OFF \
-DITK_USE_PATENTED:BOOL=ON \
-DBUILD_SHARED_LIBS:BOOL=OFF \
-DCMAKE_OSX_ARCHITECTURES:STRING=i386 \
-DCMAKE_BUILD_TYPE:STRING=Debug \
.
#-DCMAKE_OSX_ARCHITECTURES:STRING=i386,x86_64



xcodebuild -project ITK.xcodeproj -target ALL_BUILD -arch i386 GCC_SYMBOLS_PRIVATE_EXTERN=YES


